# Use the official Python image
FROM python:3.12-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the client script into the container
COPY client.py .

# Run the client.py when the container starts
CMD ["python", "client.py"]
