# Use the official PostgreSQL image
FROM postgres:latest

# Environment variables for default user, password, and database will be provided through docker-compose.yml
# Expose port 5432 (inside the container)
EXPOSE 5432
