version: "3.8"


services:
  ubuntu:
    container_name: ubuntu
    hostname: ubuntu
    build:
      context: ubuntu
      dockerfile: ./Dockerfile
      tags:
        - "${COMPOSE_VAR_DOCKER_REPO_NAME?err}/ubuntu:hydrogen"
        - "${COMPOSE_VAR_DOCKER_REPO_NAME?err}/ubuntu:0.6"
        - "${COMPOSE_VAR_DOCKER_REPO_NAME?err}/ubuntu:0.6.4"
        - "${COMPOSE_VAR_DOCKER_REPO_NAME?err}/ubuntu:latest"
      args:
      - GIT_COMMIT=cdc3b19
    volumes:
      - cmd-history-volume:${COMMAND_HISTORY_VOLUME_MOUNT_POINT?err}
    environment:
      - CMD_HIST=${COMMAND_HISTORY_VOLUME_MOUNT_POINT?err}
    tty: true
    command: tail -f /dev/null
    env_file:
      - ".env"

  terraform:
    container_name: ubuntu-terraform
    hostname: ubuntu-terraform
    build:
      context: terraform
      dockerfile: ./Dockerfile
      tags:
        - "${COMPOSE_VAR_DOCKER_REPO_NAME?err}/ubuntu-terraform:hydrogen"
        - "${COMPOSE_VAR_DOCKER_REPO_NAME?err}/ubuntu-terraform:0.1"
        - "${COMPOSE_VAR_DOCKER_REPO_NAME?err}/ubuntu-terraform:0.1.0"
        - "${COMPOSE_VAR_DOCKER_REPO_NAME?err}/ubuntu-terraform:latest"
    volumes:
      - cmd-history-volume:${COMMAND_HISTORY_VOLUME_MOUNT_POINT?err}
    tty: true
    #command: tail -f /dev/null
    env_file:
      - ".env"
  wsl:
    container_name: ubuntu-wsl
    hostname: ubuntu-wsl
    build:
      context: wsl
      dockerfile: ./Dockerfile
      args:
        - user:${COMPOSE_VAR_USERNAME}
      tags:
        - "${COMPOSE_VAR_DOCKER_REPO_NAME?err}/ubuntu-wsl:hydrogen"
        - "${COMPOSE_VAR_DOCKER_REPO_NAME?err}/ubuntu-wsl:0.1"
        - "${COMPOSE_VAR_DOCKER_REPO_NAME?err}/ubuntu-wsl:0.1.0"
        - "${COMPOSE_VAR_DOCKER_REPO_NAME?err}/ubuntu-wsl:latest"
    volumes:
      - cmd-history-volume:${COMMAND_HISTORY_VOLUME_MOUNT_POINT?err}
    tty: true
    #command: tail -f /dev/null

volumes:
  cmd-history-volume:
    external: true
    name: ${COMPOSE_VAR_COMMAND_HISTORY_VOLUME?err}