# Use the official Python image
FROM python:3.12-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the server script into the container
COPY server.py .

# Run the server.py when the container starts
CMD ["python", "server.py"]
