version: '3.8'

services:
  server:
    build: ./server
    container_name: server
    volumes:
      - /tmp:/tmp # Share /tmp between the client and server to allow communication
    networks:
      - local-net

  client:
    build: ./client
    container_name: client
    depends_on:
      - server
    volumes:
      - /tmp:/tmp # Share /tmp between the client and server to allow communication
    networks:
      - local-net

networks:
  local-net:
    driver: bridge
