# General purpose mysql with phpmyadnin and ext volume
version: "3.8"

services:

  database:
    env_file:
      - ".env"
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_CONTAINER_NAME}
    hostname: ${MYSQL_HOST}
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - db-net
    volumes:
      - db-volume:/var/lib/mysql

  phpmyadmin:
    env_file:
      - ".env"
    image: phpmyadmin/phpmyadmin
    container_name: ${PHPMYADMIN_CONTAINER_NAME}
    hostname: ${PHPMYADMIN_HOST}
    environment:
      PMA_HOST: ${MYSQL_HOST}
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_ROOT_USER}
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_ARBITRARY: 1
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
    networks:
      - db-net

volumes:
  db-volume:
    external: true
    #name: ${MYSQL_VOLUME}

networks:
  db-net: {}